name: letsencrypt-nic build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Setup Go
      run: |
        go env -w GO111MODULE=auto
    - name: Install Go dependencies
      run: |
        go get gopkg.in/ini.v1
    - name: Compile...
      run: |
        python compile.py
