# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: letsencrypt-nic build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        pip install -r requirements
    - name: Install Go
      run: |
        apt install golang -y
    - name: Setup Go
      run: |
        go env -w GO111MODULE=auto
    - name: Install Go dependencies
      run: |
        go get gopkg.in/ini.v1
    - name: Compile...
      run: |
        python compile.py
    
    
    
    
    
    
